"""Add tags, location, is_draft, last_modified to Vacant

Revision ID: 354b2045c25e
Revises: 6e4a471fa597
Create Date: 2025-04-24 13:31:32.029700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354b2045c25e'
down_revision = '6e4a471fa597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('hours',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
        batch_op.create_foreign_key('fk_vacants_institution_email', 'institution_profiles', ['institution_email'], ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacants', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_vacants_institution_email', 'institution_profiles', ['institution_email'], ['email'])
        batch_op.alter_column('hours',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('last_modified')
        batch_op.drop_column('is_draft')
        batch_op.drop_column('tags')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
