"""Add is_confirmed

Revision ID: 3baf376b5dc2
Revises: 
Create Date: 2025-04-22 14:33:17.837077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3baf376b5dc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacants')
    op.drop_table('student_profiles')
    op.drop_table('institution_profiles')
    op.drop_table('applications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_confirmed')

    op.create_table('applications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('vacant_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['student_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['vacant_id'], ['vacants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_email', 'vacant_id', name='unique_application')
    )
    op.create_table('institution_profiles',
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('institution_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=100), nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('sector', sa.VARCHAR(length=50), nullable=True),
    sa.Column('address', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('student_profiles',
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('career', sa.VARCHAR(length=100), nullable=False),
    sa.Column('semestre', sa.INTEGER(), nullable=True),
    sa.Column('average', sa.FLOAT(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.VARCHAR(length=100), nullable=True),
    sa.Column('availability', sa.VARCHAR(length=100), nullable=True),
    sa.Column('skills', sa.TEXT(), nullable=True),
    sa.Column('portfolio_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cv_url', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('vacants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('area', sa.VARCHAR(length=50), nullable=False),
    sa.Column('hours', sa.INTEGER(), nullable=False),
    sa.Column('modality', sa.VARCHAR(length=30), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('requirements', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('institution_email', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['institution_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
