"""Add BackupLog

Revision ID: 6e4a471fa597
Revises: 904e52e526b8
Create Date: 2025-04-24 13:10:58.974361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4a471fa597'
down_revision = '904e52e526b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=10), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_log')
    # ### end Alembic commands ###
