"""Initial migration

Revision ID: 904e52e526b8
Revises: 
Create Date: 2025-04-22 18:31:51.474314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904e52e526b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('last_password_reset', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('institution_profiles',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('institution_name', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('student_profiles',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('career', sa.String(length=100), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('availability', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True),
    sa.Column('cv_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('vacants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=50), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=30), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('institution_email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['institution_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_email', sa.String(), nullable=False),
    sa.Column('vacant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['vacant_id'], ['vacants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('vacants')
    op.drop_table('student_profiles')
    op.drop_table('institution_profiles')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
