"""Add Notification model and integrate notification system

Revision ID: ade047d81920
Revises: d0bab4148033
Create Date: 2025-06-29 13:33:50.518712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade047d81920'
down_revision = 'd0bab4148033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_log')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.drop_column('feedback')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.TEXT(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('application_date')

    op.create_table('backup_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('table', sa.VARCHAR(length=50), nullable=False),
    sa.Column('operation', sa.VARCHAR(length=10), nullable=False),
    sa.Column('record_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user', sa.VARCHAR(length=100), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
