"""Add logo_url to InstitutionProfile

Revision ID: d0bab4148033
Revises: 
Create Date: 2025-06-27 02:55:02.738396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bab4148033'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institution_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institution_profiles', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
